language: java
jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

after_success:
  - mvn clean test jacoco:report coveralls:report